### ISSUE TITLE
Problen Statement

### ISSUE THREAD

**Issue by deviprasad135** [deviprasad135/CAS741#1]
@smiths https://github.com/deviprasad135/CAS741/blob/master/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.pdf

Please review

**Comment by smiths** [comment]
Hello @deviprasad135.  I've put some comments in your tex file.  I'll push it to the repo in a moment.

I like your problem statement.  In addition to the comments I made in the tex file, my only suggestion is that you clarify that you are creating a library that contains a family of linear solvers.  Your goal will be to create a simplified version of something like the gnu scientific library:

https://www.gnu.org/software/gsl/manual/html_node/Linear-Algebra.html

Rather than focus on a program that takes input and produces output, you will produce a collection of related subroutines that a calling program would then use.  As part of your testing, you will write a calling program (driver), but the deliverable makes more sense as a library.

**Comment by deviprasad135** [comment]
https://github.com/deviprasad135/CAS741/blob/master/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.pdf
Please Review.

@smiths

**Comment by smiths** [comment]
Hello Devi.  I approve your problem statement.  (Please note, you do not need to aim for a linear solver that is faster.)

**Comment by deviprasad135** [comment]
Dear Dr. Smith,
Thank you for approving my problem statement.

Thanks,
Devi
